### ISSUE TITLE
Bad relative date math?

### ISSUE THREAD

**Issue by thomcc** [badboy/whatrustisit#13]
So, this is what the site says <img width="1350" alt="Screen Shot 2022-02-21 at 10 38 51 PM" src="https://user-images.githubusercontent.com/860665/155076497-a2fd4a68-7f14-4d08-8f36-a0b5a595dc2c.png">

But its 2022-02-21 today. And 2022-02-24 is not in one day, on any timezone.

**Comment by taladar** [comment]
It is the same here currently (at two minutes before noon CET on 2022-02-22), still says "in 1 day".

**Comment by badboy** [comment]
Math is hard. I'll fix that later.

**Comment by badboy** [comment]
No idea why it showed 1 day on 2022-02-21. I can't reproduce that really (though it does use UTC, so it could have been 2022-02-22 already depending on where you are, still doesn't explain the one-off).

Anyway, I fixed it for _today_.
Might come back to it some other time to see if the calculation holds up.

**Comment by taladar** [comment]
@badboy Even if it had been 2022-02-22 already that still would be 2 days from the release on 2022-02-24.

I am currently on UTC+1 so in UTC it was about 2022-02-22 10:57 at the time the bug occurred for me or more than 37 hours from 2022-02-24 00:00. Even in UTC+13 which seems to be the earliest time zone right now it wouldn't have been within 24h of that date for me, much less for @thomcc who posted this report 4 hours earlier.

**Comment by badboy** [comment]
Again, I have no idea what happened and I couldn't reproduce it.
