### ISSUE TITLE
Make the site curl-able?

### ISSUE THREAD

**Issue by matthiasbeyer** [badboy/whatrustisit#15]
Would be nice to be able to `curl whatrustisit.com > rust-toolchain` :wink:

**Comment by TheNeikos** [comment]
Could also be `curl whatrustisit.com/{stable,beta,nightly}` or so 🤔

**Comment by badboy** [comment]
> Would be nice to be able to `curl whatrustisit.com > rust-toolchain` 😉

This couldn't work, it's statically hosted here on github and so we can't do anything dynamic like that.

> Could also be `curl whatrustisit.com/{stable,beta,nightly}` or so 🤔

I don't really get the use case, but I would take a PR for it.
