### ISSUE TITLE
Incorrect "Release notes" link

### ISSUE THREAD

**Issue by Aloso** [badboy/whatrustisit#6]
The "Release notes" link is https://github.com/rust-lang/rust/blob/1.40.0/RELEASES.md , but that tag doesn't include the release notes for Rust 1.40 yet.

The correct link is https://github.com/rust-lang/rust/blob/2f4331383466ca4ed78628f35495e86d9ac47137/RELEASES.md .

**Comment by badboy** [comment]
That's most likely because the releases.md was finished after the version was tagged (a mistake).

whatrustisit.com does the most simple thing just string-replacing the version in the URL.
I won't add logic to detect any changed link.

wontfix.
