### ISSUE TITLE
Misleading Output on Release Day

### ISSUE THREAD

**Issue by xobs** [badboy/whatrustisit#8]
I suspect today is release day, and as a result this site is giving misleading information:

![image](https://user-images.githubusercontent.com/238325/112404704-cc9f7d00-8d4b-11eb-85cb-d022bb5e8395.png)

It says the next version -- which it implies is 1.51 -- will be released in 42 days on 2021-05-06.

From what I can gather, I believe 1.51 will be released today. Or perhaps tomorrow?

Special care should be taken around the release date to ensure misleading information isn't presented. Perhaps having a confetti effect.

**Comment by badboy** [comment]
The next-release calculation is rather [simplistic](https://github.com/badboy/whatrustisit/blob/6818e33a43e64b50d3a655e666f077d0aeca4d8f/index.html.tmpl#L41-L69), which as you now saw breaks on release day!
It will fix itself in less than 24 hours.
If you want to contribute a fix I'm more then happy to merge it.

**Comment by badboy** [comment]
I manually pushed, the output is now valid again ;)

**Comment by xobs** [comment]
Thanks! Man, time is hard.
